[build]
command = "npm run build"
publish = "dist"

[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=3600"


[[redirects]]
  from = "/ads.txt"
  to = "/ads.txt"
  status = 200
  force = true